[project]
name = "al-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-json-logger>=4.0.0",
    "rich>=14.2.0",
    "textual>=7.3.0",
]
